### ISSUE TITLE
Locale/translations need cleaning up

### ISSUE THREAD

**Issue by cleary** [DeBortoliWines/dotProject_plus#2]
In system config, the locale is set to en, but some menu items are not showing the correct translation:
![brewery fibre path1](https://user-images.githubusercontent.com/2577966/33196719-24be1dba-d135-11e7-9ad5-06cb08015b80.png)

**Comment by rafaelqg** [comment]
This had been fixed by updating the file "/style/default/header.php". Actually the file with the correct code was in the "dotproject_plus" style/theme. So it was necessary just to update the code in the default style file.
![translation_header](https://user-images.githubusercontent.com/19318978/35185798-cd46b036-fdf0-11e7-89e2-32f8ccdbf1e2.png)
